scripts/run_inference.sh: line 9: python: command not found
