开始数据处理流程: Sun Dec 15 10:56:27 CST 2024
Traceback (most recent call last):
  File "/Users/zxw/code/gpt_by_ai/src/crawler.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/Users/zxw/code/gpt_by_ai/src/preprocessor.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
