/Users/zxw/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Using device: mps
Traceback (most recent call last):
  File "/Users/zxw/code/gpt_by_ai/src/train.py", line 78, in <module>
    main() 
  File "/Users/zxw/code/gpt_by_ai/src/train.py", line 75, in main
    train(config, model, train_dataset)
  File "/Users/zxw/code/gpt_by_ai/src/train.py", line 22, in train
    train_loader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True)
  File "/Users/zxw/Library/Python/3.9/lib/python/site-packages/torch/utils/data/dataloader.py", line 350, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/Users/zxw/Library/Python/3.9/lib/python/site-packages/torch/utils/data/sampler.py", line 142, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "/Users/zxw/Library/Python/3.9/lib/python/site-packages/torch/utils/data/sampler.py", line 149, in num_samples
    return len(self.data_source)
ValueError: __len__() should return >= 0
